In [10]:
import pandas as pd
from sqlalchemy import create_engine

In [27]:
engine= create_engine("mysql+mysqlconnector://root:Sivesh2308@localhost/sales_analysis")

In [36]:
query = """
SELECT
    o.invoice_no,
    o.invoice_date,
    c.customer_id,
    c.country,
    oi.quantity,
    oi.unit_price
FROM orders o
JOIN order_items oi ON o.invoice_no = oi.invoice_no
JOIN customers c ON o.customer_id = c.customer_id
"""
df = pd.read_sql(query, engine)
df.head()

  invoice_no invoice_date customer_id           country  quantity  unit_price
0     489434   2009-12-01       13085  United Kingdom\r        12        6.95
1     489434   2009-12-01       13085  United Kingdom\r        12        6.75
2     489434   2009-12-01       13085  United Kingdom\r        12        6.75
3     489434   2009-12-01       13085  United Kingdom\r        48        2.10
4     489434   2009-12-01       13085  United Kingdom\r        24        1.25

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70809 entries, 0 to 70808
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   invoice_no    70809 non-null  object
 1   invoice_date  70809 non-null  object
 2   customer_id   70809 non-null  object
 3   country       70809 non-null  object
 4   quantity      70809 non-null  int64
 5   unit_price    70809 non-null  float64
 6   revenue       70809 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 3.8+ MB

In [21]:
df.isna().sum()

invoice_no      0
invoice_date    0
customer_id     0
country         0
quantity        0
unit_price      0
dtype: int64

In [22]:
df.describe()

           quantity    unit_price
count  70809.000000  70809.000000
mean      15.139333      3.423511
std      130.387810     36.268541
min        1.000000      0.000000
25%        2.000000      1.250000
50%        5.000000      2.100000
75%       12.000000      3.750000
max    19152.000000   8985.600000

In [23]:
df['invoice_date']= pd.to_datetime(df['invoice_date'])

In [25]:
df=df[df['quantity']>0]
df=df[df['unit_price']>0]

In [37]:
df['revenue'] = df['quantity'] * df['unit_price']

In [38]:
total_revenue_all = df['revenue'].sum()

In [39]:
clean_df = df.dropna(subset=['customer_id', 'invoice_no'])

In [40]:
total_revenue_clean = clean_df['revenue'].sum()

In [41]:
total_revenue_all, total_revenue_clean

(np.float64(1630006.1399999997), np.float64(1630006.1399999997))

In [42]:
df.head(200)

,invoice_no,invoice_date,customer_id,country,quantity,unit_price,revenue
0,489434,2009-12-01,13085,United Kingdom\r,12,6.95,83.40
1,489434,2009-12-01,13085,United Kingdom\r,12,6.75,81.00
2,489434,2009-12-01,13085,United Kingdom\r,12,6.75,81.00
3,489434,2009-12-01,13085,United Kingdom\r,48,2.10,100.80
4,489434,2009-12-01,13085,United Kingdom\r,24,1.25,30.00
...,...,...,...,...,...,...,...
195,489460,2009-12-01,16167,United Kingdom\r,576,0.21,120.96
196,489460,2009-12-01,16167,United Kingdom\r,8,6.75,54.00
197,489460,2009-12-01,16167,United Kingdom\r,3,4.95,14.85
198,489460,2009-12-01,16167,United Kingdom\r,3,4.95,14.85
199,489460,2009-12-01,16167,United Kingdom\r,4,6.75,27.00

In [44]:
df.to_csv("../data/clean_sales_data.csv", index=False)